#!/bin/sh
# $Id: Distro,v 1.3 2006/03/30 12:12:33 jettero Exp $

./distclean
perl Makefile.PL && make dist

mkdir -p dist

    n=`ls My*Easy*gz`;
    date=`date`;
    cat Easy.pm | pod2html > ./dist/Easy.html
    rm -vf pod* ./dist/My*Easy*gz
    mv -v My*gz ./dist
cat > ./dist/Easy.b.html << EOF
<p>
This (<a href="$n">$n</a>) is something I've been using over and over.  I don't
remember how I used to live without it.  So, I give it to you.
Don't use it if you don't like it! :)  This namespace has been discontinued.  It
is still available under the name DBIx::Easy::MySQL.
Check out the man page: <a href="?eo_cat=Easy.html">MySQL::Easy module</a>.
Last updated on $date
EOF

ssh mei.net "(cd /home/dillhome/voltar/html/PerlModules/; rm *My*Easy*)"
scp dist/* mei.net:/home/dillhome/voltar/html/PerlModules/
ssh mei.net "(cd /home/dillhome/voltar/html/PerlModules/; chmod 644 *.html *.gz)"

rm -rvf dist
