#!/bin/sh
# $Id: Distro,v 1.3 2002/01/17 17:55:22 jettero Exp $

./distclean
perl Makefile.PL && make dist

if [ -d ~/www/PerlModules ]; then
    n=`ls My*Easy*gz`;
    date=`date`;
    cat Easy.pm | pod2html > ~/www/PerlModules/Easy.html
    rm -vf pod* ~/www/PerlModules/My*Easy*gz
    mv -v My*gz ~/www/PerlModules
cat > ~/www/PerlModules/Easy.b.html << EOF
<p>
This (<a href="$n">$n</a>) is something I've been using over and over.  I don't
remember how I used to live without it.  So, I give it to you.
Don't use it if you don't like it! :)  
Check out the man page: <a href="?eo_cat=Easy.html">MySQL::Easy module</a>.
Last updated on $date
EOF
    chmod -v 644 ~/www/PerlModules/Easy.* ~/www/PerlModules/My*gz
fi
