--- #YAML:1.0
name:               MySQL-Easy
version:            2.1008
abstract:           ~
author:  []
license:            LGPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    common::sense:  0
    DBD::mysql:     0
    DBI:            0
    perl:           5.006001
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - mysql
    - helper
    - easy
